### ISSUE TITLE
Data Base fail

### ISSUE THREAD

**Issue by jmcerpa** [CloudOpting/deploy-cloudopting#3]
manager_db | The files belonging to this database system will be owned by user "postgres".
manager_db | This user must also own the server process.
manager_db | 
manager_db | The database cluster will be initialized with locale "en_US.utf8".
manager_db | The default database encoding has accordingly been set to "UTF8".
manager_db | The default text search configuration will be set to "english".
manager_db | 
manager_db | Data page checksums are disabled.
manager_db | 
manager_db | fixing permissions on existing directory /var/lib/postgresql/data ... ok
manager_db | creating subdirectories ... ok
manager_db | selecting default max_connections ... 100
manager_db | selecting default shared_buffers ... 128MB
manager_db | selecting dynamic shared memory implementation ... posix
manager_db | creating configuration files ... ok
manager_db | creating template1 database in /var/lib/postgresql/data/base/1 ... ok
manager_db | initializing pg_authid ... ok
manager_db | initializing dependencies ... ok
manager_db | creating system views ... ok
manager_db | loading system objects' descriptions ... ok
manager_db | creating collations ... ok
manager_db | creating conversions ... ok
manager_db | creating dictionaries ... ok
manager_db | setting privileges on built-in objects ... ok
manager_db | creating information schema ... ok
manager_db | loading PL/pgSQL server-side language ... ok
manager_db | vacuuming database template1 ... ok
manager_db | copying template1 to template0 ... ok
manager_db | copying template1 to postgres ... ok
manager_db | syncing data to disk ... ok
manager_db | 
manager_db | Success. You can now start the database server using:
manager_db | 
manager_db |     pg_ctl -D /var/lib/postgresql/data -l logfile start
manager_db | 
manager_db | 
manager_db | WARNING: enabling "trust" authentication for local connections
manager_db | You can change this by editing pg_hba.conf or using the option -A, or
manager_db | --auth-local and --auth-host, the next time you run initdb.
manager_db | waiting for server to start....LOG:  database system was shut down at 2016-02-10 10:22:15 UTC
manager_db | LOG:  MultiXact member wraparound protections are now enabled
manager_db | LOG:  database system is ready to accept connections
manager_db | LOG:  autovacuum launcher started
manager_db |  done
manager_db | server started
manager_db | ALTER ROLE
manager_db | 
manager_db | 
manager_db | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/populate.sql
manager_db | CREATE DATABASE
manager_db | ALTER DATABASE
manager_db | ERROR:  schema "public" already exists
manager_db | STATEMENT:  CREATE SCHEMA public;
manager_db | ERROR:  schema "public" already exists
manager_db exited with code 0

**Comment by xeviscc** [comment]
Seems that the error comes from the file: https://github.com/CloudOpting/deploy-cloudopting/blob/master/database/files/initial_script.sql

**Comment by xeviscc** [comment]
Catalin, could you check which are the needed sentences for this initial script?

**Comment by cpopsa** [comment]
Fixed. I modified initial_script.sql and V0.1__DbInit.sql
